namespace MeshCoreSharp.Protocol;

public enum CommandType : byte
{
    AppStart = 1,
    SendTextMessage = 2,
    SendChannelTextMessage = 3,
    GetContacts = 4,
    GetDeviceTime = 5,
    SetDeviceTime = 6,
    SendSelfAdvertisement = 7,
    SetAdvertisementName = 8,
    AddOrUpdateContact = 9,
    SyncNextMessage = 10,
    SetRadioParameters = 11,
    SetRadioTxPower = 12,
    ResetPath = 13,
    SetAdvertisementLocation = 14,
    RemoveContact = 15,
    ShareContact = 16,
    ExportContact = 17,
    ImportContact = 18,
    Reboot = 19,
    GetBatteryAndStorage = 20,
    SetTuningParameters = 21,
    DeviceQuery = 22,
    ExportPrivateKey = 23,
    ImportPrivateKey = 24,
    SendRawData = 25,
    SendLogin = 26,
    SendStatusRequest = 27,
    HasConnection = 28,
    Logout = 29,
    GetContactByKey = 30,
    GetChannel = 31,
    SetChannel = 32,
    SignStart = 33,
    SignData = 34,
    SignFinish = 35,
    SendTracePath = 36,
    SetDevicePin = 37,
    SetOtherParameters = 38,
    SendTelemetryRequest = 39,
    GetCustomVariables = 40,
    SetCustomVariable = 41,
    GetAdvertisementPath = 42,
    GetTuningParameters = 43,
    SendBinaryRequest = 50,
    FactoryReset = 51,
    PathDiscovery = 52,
    SetFloodScopeKey = 54,
    SendControlData = 55,
    GetStats = 56,
    SendAnonymousRequest = 57,
    SetAutoAddConfig = 58,
    GetAutoAddConfig = 59,
    GetAllowedRepeatFrequency = 60,
    SetPathHashMode = 61,
    SendChannelData = 62,
    SetDefaultFloodScope = 63,
    GetDefaultFloodScope = 64,
    SendRawPacket = 65,

    // Present in meshcore_py but not in the current baseline companion firmware.
    RunCliCommand = 66,
}
