namespace MeshCoreSharp.Protocol;

public enum PacketType : byte
{
    Ok = 0x00,
    Error = 0x01,
    ContactStart = 0x02,
    Contact = 0x03,
    ContactEnd = 0x04,
    SelfInfo = 0x05,
    MessageSent = 0x06,
    ContactMessageReceived = 0x07,
    ChannelMessageReceived = 0x08,
    CurrentTime = 0x09,
    NoMoreMessages = 0x0A,
    ContactUri = 0x0B,
    BatteryAndStorage = 0x0C,
    DeviceInfo = 0x0D,
    PrivateKey = 0x0E,
    Disabled = 0x0F,
    ContactMessageReceivedV3 = 0x10,
    ChannelMessageReceivedV3 = 0x11,
    ChannelInfo = 0x12,
    SignStart = 0x13,
    Signature = 0x14,
    CustomVariables = 0x15,
    AdvertisementPath = 0x16,
    TuningParameters = 0x17,
    Stats = 0x18,
    AutoAddConfig = 0x19,
    AllowedRepeatFrequency = 0x1A,
    ChannelDataReceived = 0x1B,
    DefaultFloodScope = 0x1C,
    CliReply = 0x1D,

    Advertisement = 0x80,
    PathUpdated = 0x81,
    Ack = 0x82,
    MessagesWaiting = 0x83,
    RawData = 0x84,
    LoginSuccess = 0x85,
    LoginFailed = 0x86,
    StatusResponse = 0x87,
    LogData = 0x88,
    TraceData = 0x89,
    NewAdvertisement = 0x8A,
    TelemetryResponse = 0x8B,
    BinaryResponse = 0x8C,
    PathDiscoveryResponse = 0x8D,
    ControlData = 0x8E,
    ContactDeleted = 0x8F,
    ContactsFull = 0x90,
}
